const prisma = require('../prisma/prisma');
const supabase = require('../config/supabase');
const path = require('path');

const BUCKET_NAME = 'paymentSlip';

const uploadToSupabase = async (file) => {
    const fileName = `${Date.now()}-${Math.round(Math.random() * 1e9)}${path.extname(file.originalname)}`;
    const { data, error } = await supabase.storage
        .from(BUCKET_NAME)
        .upload(fileName, file.buffer, {
            contentType: file.mimetype,
            cacheControl: '3600',
            upsert: false
        });

    if (error) throw error;

    const { data: { publicUrl } } = supabase.storage
        .from(BUCKET_NAME)
        .getPublicUrl(fileName);

    return publicUrl;
};

exports.createOrder = async (req, res) => {
    try {
        let { 
            id, // Order ID generated by client (e.g., ORD-20260511-XXXX)
            items, 
            subtotal, 
            discount, 
            total, 
            paymentMethod, 
            paymentSlip,
            receivedAmount,
            changeDue,
            notes,
            customerId 
        } = req.body;
        const storeId = req.user.storeId;

        if (!storeId) {
            return res.status(400).json({ message: 'User does not belong to a store' });
        }

        // Handle File Upload if exists
        if (req.file) {
            paymentSlip = await uploadToSupabase(req.file);
        }

        // Parse items if it's a string (from multipart/form-data)
        if (typeof items === 'string') {
            items = JSON.parse(items);
        }

        // 1. Validate items and calculate total cost / profit
        let calculatedTotalCost = 0;
        
        // We use a transaction to ensure all operations succeed or none
        const result = await prisma.$transaction(async (tx) => {
            
            // Process each item
            for (const item of items) {
                const product = await tx.product.findFirst({
                    where: { 
                        id: item.id,
                        storeId
                    }
                });

                if (!product) throw new Error(`Product with ID ${item.id} not found in this store`);
                if (product.stock < item.quantity) throw new Error(`Insufficient stock for ${product.name}`);

                calculatedTotalCost += (product.cost * item.quantity);

                // Update Stock
                const updatedProduct = await tx.product.update({
                    where: { id: item.id },
                    data: {
                        stock: { decrement: item.quantity }
                    }
                });

                // Record Stock Movement
                await tx.stockMovement.create({
                    data: {
                        productId: item.id,
                        productName: product.name,
                        type: 'SALE',
                        quantity: item.quantity,
                        previousStock: product.stock,
                        newStock: updatedProduct.stock,
                        costAtTime: product.cost,
                        note: `Sale Order: ${id}`,
                        storeId
                    }
                });
            }

            const profit = parseFloat(total) - calculatedTotalCost;

            // Create Order
            const order = await tx.order.create({
                data: {
                    id,
                    items,
                    subtotal: parseFloat(subtotal),
                    discount: parseFloat(discount || 0),
                    total: parseFloat(total),
                    totalCost: calculatedTotalCost,
                    profit,
                    paymentMethod,
                    paymentSlip,
                    receivedAmount: receivedAmount ? parseFloat(receivedAmount) : null,
                    changeDue: changeDue ? parseFloat(changeDue) : null,
                    notes,
                    customerId: customerId ? parseInt(customerId) : null,
                    storeId
                }
            });

            // Update Customer Points if applicable
            if (customerId) {
                const store = await tx.store.findUnique({
                    where: { id: storeId }
                });

                const settings = store || { 
                    loyaltyPointType: 'amount', 
                    loyaltyPointRate: 20 
                };
                
                let pointsEarned = 0;
                if (settings.loyaltyPointType === 'item') {
                    // Logic: 1 Item = X Points (Sum of quantities * rate)
                    const totalQuantity = items.reduce((sum, item) => sum + item.quantity, 0);
                    pointsEarned = Math.floor(totalQuantity * settings.loyaltyPointRate);
                } else {
                    // Logic: X Amount = 1 Point (Total / rate)
                    pointsEarned = Math.floor(parseFloat(total) / settings.loyaltyPointRate);
                }

                if (pointsEarned > 0) {
                    const customer = await tx.customer.update({
                        where: { 
                            id: parseInt(customerId)
                            // storeId check is implicit if we trust customerId belongs to store
                        },
                        data: {
                            points: { increment: pointsEarned }
                        }
                    });

                    await tx.pointLog.create({
                        data: {
                            customerId: parseInt(customerId),
                            amount: pointsEarned,
                            after: customer.points,
                            note: `Earned from Order: ${id} (${settings.loyaltyPointType === 'item' ? 'Item based' : 'Amount based'})`,
                            storeId
                        }
                    });
                }
            }

            return order;
        });

        res.status(201).json(result);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Transaction Failed', error: err.message });
    }
};

exports.listOrders = async (req, res) => {
    try {
        const { start, end } = req.query; // Date filters
        const storeId = req.user.storeId;
        let where = { storeId };
        
        if (start && end) {
            where.timestamp = {
                gte: new Date(start),
                lte: new Date(end)
            };
        }

        const orders = await prisma.order.findMany({
            where,
            include: {
                customer: true
            },
            orderBy: { timestamp: 'desc' }
        });
        res.json(orders);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
};

exports.getOrder = async (req, res) => {
    try {
        const { id } = req.params;
        const storeId = req.user.storeId;
        const order = await prisma.order.findFirst({
            where: { id, storeId },
            include: { customer: true }
        });
        if (!order) return res.status(404).json({ message: 'Order not found' });
        res.json(order);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
};

exports.voidOrder = async (req, res) => {
    try {
        const { id } = req.params;
        const storeId = req.user.storeId;
        
        const result = await prisma.$transaction(async (tx) => {
            const order = await tx.order.findFirst({
                where: { id, storeId }
            });

            if (!order) throw new Error('Order not found');
            if (order.status === 'voided') throw new Error('Order is already voided');

            // Restore Stock
            const items = order.items;
            for (const item of items) {
                const product = await tx.product.findFirst({ 
                    where: { 
                        id: item.id,
                        storeId
                    } 
                });
                
                if (!product) continue; // Should not happen

                const updatedProduct = await tx.product.update({
                    where: { id: item.id },
                    data: { stock: { increment: item.quantity } }
                });

                await tx.stockMovement.create({
                    data: {
                        productId: item.id,
                        productName: product.name,
                        type: 'VOID_RESTORE',
                        quantity: item.quantity,
                        previousStock: product.stock,
                        newStock: updatedProduct.stock,
                        costAtTime: product.cost,
                        note: `Void Order: ${id}`,
                        storeId
                    }
                });
            }

            // Deduct Points if customer was involved
            if (order.customerId) {
                const store = await tx.store.findUnique({
                    where: { id: storeId }
                });
                const settings = store || { loyaltyPointRate: 20 };
                const pointsToDeduct = Math.floor(order.total / settings.loyaltyPointRate);

                if (pointsToDeduct > 0) {
                    const customer = await tx.customer.update({
                        where: { id: order.customerId },
                        data: { points: { decrement: pointsToDeduct } }
                    });

                    await tx.pointLog.create({
                        data: {
                            customerId: order.customerId,
                            amount: -pointsToDeduct,
                            after: customer.points,
                            note: `Deducted from Voided Order: ${id}`,
                            storeId
                        }
                    });
                }
            }

            return await tx.order.update({
                where: { id },
                data: {
                    status: 'voided',
                    voidedAt: new Date()
                }
            });
        });

        res.json(result);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Voiding Failed', error: err.message });
    }
};

