const prisma = require('../prisma/prisma');

exports.createOrder = async (req, res) => {
    try {
        const { 
            id, // Order ID generated by client (e.g., ORD-20260511-XXXX)
            items, 
            subtotal, 
            discount, 
            total, 
            paymentMethod, 
            paymentSlip,
            receivedAmount,
            changeDue,
            notes,
            customerId 
        } = req.body;

        // 1. Validate items and calculate total cost / profit
        let calculatedTotalCost = 0;
        
        // We use a transaction to ensure all operations succeed or none
        const result = await prisma.$transaction(async (tx) => {
            
            // Process each item
            for (const item of items) {
                const product = await tx.product.findUnique({
                    where: { id: item.id }
                });

                if (!product) throw new Error(`Product with ID ${item.id} not found`);
                if (product.stock < item.quantity) throw new Error(`Insufficient stock for ${product.name}`);

                calculatedTotalCost += (product.cost * item.quantity);

                // Update Stock
                const updatedProduct = await tx.product.update({
                    where: { id: item.id },
                    data: {
                        stock: { decrement: item.quantity }
                    }
                });

                // Record Stock Movement
                await tx.stockMovement.create({
                    data: {
                        productId: item.id,
                        productName: product.name,
                        type: 'SALE',
                        quantity: item.quantity,
                        previousStock: product.stock,
                        newStock: updatedProduct.stock,
                        costAtTime: product.cost,
                        note: `Sale Order: ${id}`
                    }
                });
            }

            const profit = total - calculatedTotalCost;

            // Create Order
            const order = await tx.order.create({
                data: {
                    id,
                    items,
                    subtotal,
                    discount,
                    total,
                    totalCost: calculatedTotalCost,
                    profit,
                    paymentMethod,
                    paymentSlip,
                    receivedAmount,
                    changeDue,
                    notes,
                    customerId: customerId ? parseInt(customerId) : null
                }
            });

            // Update Customer Points if applicable
            if (customerId) {
                const settings = await tx.storeSettings.findFirst() || { loyaltyPointRate: 20 };
                const pointsEarned = Math.floor(total / settings.loyaltyPointRate);

                if (pointsEarned > 0) {
                    const customer = await tx.customer.update({
                        where: { id: parseInt(customerId) },
                        data: {
                            points: { increment: pointsEarned }
                        }
                    });

                    await tx.pointLog.create({
                        data: {
                            customerId: parseInt(customerId),
                            amount: pointsEarned,
                            after: customer.points,
                            note: `Earned from Order: ${id}`
                        }
                    });
                }
            }

            return order;
        });

        res.status(201).json(result);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Transaction Failed', error: err.message });
    }
};

exports.listOrders = async (req, res) => {
    try {
        const { start, end } = req.query; // Date filters
        let where = {};
        
        if (start && end) {
            where.timestamp = {
                gte: new Date(start),
                lte: new Date(end)
            };
        }

        const orders = await prisma.order.findMany({
            where,
            include: {
                customer: true
            },
            orderBy: { timestamp: 'desc' }
        });
        res.json(orders);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
};

exports.getOrder = async (req, res) => {
    try {
        const { id } = req.params;
        const order = await prisma.order.findUnique({
            where: { id },
            include: { customer: true }
        });
        if (!order) return res.status(404).json({ message: 'Order not found' });
        res.json(order);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
};

exports.voidOrder = async (req, res) => {
    try {
        const { id } = req.params;
        
        const result = await prisma.$transaction(async (tx) => {
            const order = await tx.order.findUnique({
                where: { id }
            });

            if (!order) throw new Error('Order not found');
            if (order.status === 'voided') throw new Error('Order is already voided');

            // Restore Stock
            const items = order.items;
            for (const item of items) {
                const product = await tx.product.findUnique({ where: { id: item.id } });
                
                const updatedProduct = await tx.product.update({
                    where: { id: item.id },
                    data: { stock: { increment: item.quantity } }
                });

                await tx.stockMovement.create({
                    data: {
                        productId: item.id,
                        productName: product.name,
                        type: 'VOID_RESTORE',
                        quantity: item.quantity,
                        previousStock: product.stock,
                        newStock: updatedProduct.stock,
                        costAtTime: product.cost,
                        note: `Void Order: ${id}`
                    }
                });
            }

            // Deduct Points if customer was involved
            if (order.customerId) {
                const settings = await tx.storeSettings.findFirst() || { loyaltyPointRate: 20 };
                const pointsToDeduct = Math.floor(order.total / settings.loyaltyPointRate);

                if (pointsToDeduct > 0) {
                    const customer = await tx.customer.update({
                        where: { id: order.customerId },
                        data: { points: { decrement: pointsToDeduct } }
                    });

                    await tx.pointLog.create({
                        data: {
                            customerId: order.customerId,
                            amount: -pointsToDeduct,
                            after: customer.points,
                            note: `Deducted from Voided Order: ${id}`
                        }
                    });
                }
            }

            return await tx.order.update({
                where: { id },
                data: {
                    status: 'voided',
                    voidedAt: new Date()
                }
            });
        });

        res.json(result);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Voiding Failed', error: err.message });
    }
};
